# Generated by Django 5.2.1 on 2025-05-30 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_editora_cidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='nome',
            new_name='titulo',
        ),
    ]
