# Generated by Django 5.2.1 on 2025-05-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_editora_cidade_alter_editora_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='titulo',
            field=models.CharField(max_length=300),
        ),
    ]
